name: moviex
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  get_it: ^7.2.0
  http_parser: ^4.0.1
  intl: ^0.17.0
  pretty_dio_logger: ^1.1.1
  sliver_fab: ^1.0.0
  youtube_player_flutter: ^8.1.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mockito: any
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0
  build_runner:

flutter:
  uses-material-design: true
  generate: true
