name: moviex
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cached_network_image: ^3.2.1
  custom_navigation_bar: ^0.8.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^1.0.4
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^1.1.3
  flutter_swiper_view: ^1.1.8
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http_parser: ^4.0.1
  intl: ^0.17.0
  json_annotation: ^4.6.0
  path_provider: ^2.0.11
  persistent_bottom_nav_bar: ^4.0.2
  pretty_dio_logger: ^1.1.1
  riverpod: ^1.0.3
  sliver_fab: ^1.0.0
  timeago: ^3.3.0
  visible_opacity: ^2.0.0
  youtube_player_flutter: ^8.1.0

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: any
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  hive_generator: any
  json_serializable: ^6.3.1
  mockito: any
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/jsons/
    - assets/icons/
