name: moviex
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^1.0.4
  get_it: ^7.2.0
  http_parser: ^4.0.1
  intl: ^0.17.0
  json_annotation: ^4.6.0
  pretty_dio_logger: ^1.1.1
  riverpod: ^1.0.3
  sliver_fab: ^1.0.0
  youtube_player_flutter: ^8.1.0

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: null
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  json_serializable: ^6.3.1
  mockito: any
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
